### ISSUE TITLE
Sugerencia mejora: parametros de hora inicial-final

### ISSUE THREAD

**Issue by mr-E** [jjlopez/descargar-cfdi#1]
No he probado tu proyecto aún.
Pero me surge esta duda (la cual puede aplicar incluso en admin-cfdi):

¿Es posible añadir como parametro la hora inicial/final del día a descargar? Esto porque a como van las cosas, pronto llegaremos a recibir +500 comprobantes diarios. Y seria muy útil el poder indicar el rango de horas (inicial y final) para descargar en dos partes cuando se tienen +500 comprobantes.
Saludos, gracias!

**Comment by jjlopez** [comment]
Si es posible con el método descargarPorFiltros. 

Mira este ejemplo.

Descargar los xml del día 16/02/2015 que tengan la hora de creación entre las 15:10:07 y las 22:14:10 horas

``` python
from ServicioCfdi import ServicioCfdi
from FiltrosRecibidos import FiltrosRecibidos

servicio = ServicioCfdi('RFC', 'Contrasena')
#Definir filtros personalizados
filtros=FiltrosRecibidos()
filtros.annio='2015'
filtros.mes='2'
filtros.dia='16'
filtros.horaInicial='15'
filtros.minutoInicial='10'
filtros.segundoInicial='7'
filtros.horaFinal='22'
filtros.minutoFinal='14'
filtros.segundoFinal='10'

if not servicio.descargarPorFiltros('/home/usuario/xml/', filtros):
    print("Ha ocurrido el siguiente error: " + servicio.obtieneMensajeError())
else:
    descargados = servicio.obtieneListaDocumentosDescargados()
    print("XML Descargados: " + str(len(descargados)))
```

¡Saludos!

**Comment by mr-E** [comment]
Wow! Gracias! a la primera oportunidad lo uso y pongo mis resultados.
