### ISSUE TITLE
Solo descarga 500 comprobantes a la vez

### ISSUE THREAD

**Issue by saitluis** [jjlopez/descargar-cfdi#7]
Que tal buenas tardes. 

Antes que nada gracias por aportar esta valiosa herramienta que utilizamos en nuestra empresa, quisiera ver si alguien mas a notado que solo puede descargar de 500 comprobantes a la vez y ver si tienen alguna idea de porque pasa esto. 

Saludos

**Comment by mr-E** [comment]
Es limitación del propio portal del SAT.

**Comment by saitluis** [comment]
Muchas gracias
